### ISSUE TITLE
yamllint Errors

### ISSUE THREAD

**Issue by gdpak** [ansible-network/cisco_ios#72]
Issue to track Yamlint issues in existing code. Probably they get introduced before we enabled lint check on Zuul.

./tasks/configure_user.yaml
  5:9       error    too many spaces after colon  (colons)
  35:1      error    trailing spaces  (trailing-spaces)

./tasks/cloud_vpn/providers/csr/initiator/add_host.yaml
  19:1      error    too many blank lines (1 > 0)  (empty-lines)

./tasks/net_operations/pre_config_sink_device.yaml
  4:7       error    too many spaces before colon  (colons)
  21:42     error    trailing spaces  (trailing-spaces)

./tasks/net_operations/sink_packet_capture_logs.yaml
  7:7       error    too many spaces before colon  (colons)
  17:5      error    wrong indentation: expected 6 but found 4  (indentation)
  27:5      error    wrong indentation: expected 6 but found 4  (indentation)
  29:1      error    too many blank lines (1 > 0)  (empty-lines)

./tasks/net_operations/parse_validate_acl.yaml
  10:7      error    too many spaces before colon  (colons)
  12:7      error    wrong indentation: expected 4 but found 6  (indentation)

./tests/config_manager/config_manager/tasks/load.yml
  10:15     error    too many spaces after colon  (colons)
  20:11     error    too many spaces after colon  (colons)
  36:11     error    too many spaces after colon  (colons)
  50:9      error    trailing spaces  (trailing-spaces)
  53:15     error    too many spaces after colon  (colons

./tests/config_manager/config_manager/tasks/get.yml
  4:11      error    too many spaces after colon  (colons)

./tests/parser_templates/cli/show_interfaces/main.yaml
  1:1       error    too many blank lines (1 > 0)  (empty-lines)

./tests/parser_templates/cli/show_ip_vrf_detail/main.yaml
   12:5      error    wrong indentation: expected 6 but found 4  (indentation)

./includes/args_adapter.yaml
  14:1      error    too many blank lines (1 > 0)  (empty-lines)

./includes/init.yaml
  23:7      error    wrong indentation: expected 4 but found 6  (indentation)
  32:7      error    wrong indentation: expected 4 but found 6  (indentation)
./parser_templates/config/show_run_interface.yaml
   11:3      error    wrong indentation: expected 4 but found 2  (indentation)
  71:5      error    wrong indentation: expected 6 but found 4  (indentation)

./parser_templates/net_operations/show_ip_access_list.yaml
  33:231    error    line too long (516 > 230 characters)  (line-length)

./parser_templates/cli/show_lldp_neighbors_detail.yaml
  54:1      error    too many blank lines (2 > 0)  (empty-lines)

./parser_templates/cli/show_ip_vrf_detail.yaml
  139:1     error    too many blank lines (1 > 0)  (empty-lines)

./handlers/main.yml
  2:46      error    no new line character at the end of file  (new-line-at-end-of-file)

**Comment by pabelanger** [comment]
Fixed in #73 and we now gate on yamllint
